<!-- head.inc -->
<!-- portal bar -->
<link rel="stylesheet" type="text/css" media="all" href="http://bbt.krishna.com/portalbar/portalbar.css" />
<!-- 
script language="JavaScript" type="text/javascript" src="http://bbt.krishna.com/portalbar/portalbar.js"></script>
-->
<style type="text/css">
/* font fix 
.portaldiv { font-size: 100%; }
*/
</style>


<script language="JavaScript" type="text/javascript" src="/js/global.js"></script>

<!-- /head.inc -->
