<!-- portalbar -->
<div id="not_portalbar"><img id="portalimg" src="http://www.iskcon.com/images/global_bar.gif" alt="" height="24" width="780" border="0" usemap="#portalmap" />
	<map id="portalmap" name="portalmap">
		<area coords="0,0,116,24" href="http://www.krishna.com/" title="The science of devotion to Krishna: online books, art gallery, radio, video streams, and gift store." alt="Krishna.com" onmouseover="showDescription(this.title)" onMouseOut="hideDescription()" />
		<area coords="116,0,225,24" href="http://www.iskcon.com/" title="The official site of the Hare Krishna Movement." alt="ISKCON.com" onmouseover="showDescription(this.title)" onMouseOut="hideDescription()" />
		<area coords="225,0,312,24" href="http://www.bbt.info/" title="The Bhaktivedanta Book Trust International." alt="BBT.info" onmouseover="showDescription(this.title)" onMouseOut="hideDescription()" />
	</map>
	<div id="infoDiv"></div>
</div>
<!-- /portalbar -->
